apiVersion: apps/v1
kind: Deployment
metadata:
  name: a
  namespace: makaveli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: A
  template:
    metadata:
      labels:
        app: A
    spec:
      containers:
        - name: service
          env:
            - name: DEPENDENCIES
              value: http://10.45.126.177:30002
          image: wylswz/cnbase-spring
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-a
  namespace: makaveli
spec:
  type: NodePort
  selector:
    app: A
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b
  namespace: makaveli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: B
  template:
    metadata:
      labels:
        app: B
    spec:
      containers:
        - name: service
          image: wylswz/cnbase-spring
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-b
  namespace: makaveli
spec:
  type: NodePort
  selector:
    app: B
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30002